import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/cmponents/Navbar";

import 'remixicon/fonts/remixicon.css'

const FontPoppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata = {
  title: "Company Profile",
  description: "Generated by Rokhim_Dev",
  const: {
    icon: '/favicon.png',
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${FontPoppins.className} antialiased`}>
        <Navbar />
        <div className="container mx-auto px-4">{children}</div>
      </body>
    </html>
  );
}
